expt_num = 3
Change the 1st convolution in 1st conv block become 1 convolution layer
ValueError: Negative dimension size caused by subtracting 3 from 2 for 'conv3d_31/convolution' (op: 'Conv3D') with input shapes: [?,2,2,2,32], [3,3,3,32,32].